language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"


install:
  - pip install -r requirements.txt



before_install:
  - "export DISPLAY=:43.0"
  - "sh -e /etc/init.d/xvfb start"

script: python manage.py test
