version: '3'

services:

  app:
    env_file: .env
    build: .
    depends_on:
      - redis
    ports:
      - "8008:8008"
    volumes:
      - ./localdata:/data
      - .:/app

  redis:
    image: redis:3.2-alpine
    volumes:
      - ./redisdata:/data

volumes:
  redis_data:
